<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	  <ImplicitUsings>true</ImplicitUsings>
	  <OutputPath>..\\..\\bin</OutputPath>
	  <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="CppSharp" Version="1.1.84.17100" />
    <PackageReference Include="CppSharp.Runtime" Version="1.1.84.17100" />
    <PackageReference Include="SharpSvn.AnnotateAssembly" Version="1.14005.390">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autofac">
      <HintPath>..\..\SDK\XPloteThirdParthDLL\Autofac.dll</HintPath>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>..\..\SDK\XPloteThirdParthDLL\Serilog.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Sinks.Console">
      <HintPath>..\..\SDK\XPloteThirdParthDLL\Serilog.Sinks.Console.dll</HintPath>
    </Reference>
    <Reference Include="XPlote.Expand">
      <HintPath>..\..\SDK\XPloteThirdParthDLL\XPlote.Expand.dll</HintPath>
    </Reference>
    <Reference Include="XPlote.Framework.WPF">
      <HintPath>..\..\SDK\XPloteThirdParthDLL\XPlote.Framework.WPF.dll</HintPath>
    </Reference>
    <Reference Include="XPlote.Themes.WPF">
      <HintPath>..\..\SDK\XPloteThirdParthDLL\XPlote.Themes.WPF.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
